import { describe, expect, it } from "vitest";
import { createContextPacket } from "./contextPacket";
import { createGenerationSnapshot, isGenerationSnapshotCurrent } from "./generationSnapshot";
import { createInMemoryLocalEvidenceStore } from "../../shared/storage/inMemoryLocalEvidenceStore";
import { evidence, experience, reflection } from "../../test/fixtures";
describe("stale generation protection", () => {
  it("does not save old Evidence after Experience revision", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "Original body with context." }); const packet = createContextPacket({ currentExperience: entry, locale: "en", requestedTask: "evidence", provider: "mock" }).packet; const snapshot = createGenerationSnapshot(packet); await store.updateExperience(entry.id, { body: "Revised body with different context." }); expect(isGenerationSnapshotCurrent(snapshot, await store.getExperience(entry.id), await store.listArtifacts(entry.id))).toBe(false); const result = await store.saveArtifacts(entry.id, { evidence: [evidence("old", entry.id, "candidate")], reflections: [], patterns: [], recoveryTurns: [] }, { expectedExperienceUpdatedAt: snapshot.sourceExperienceUpdatedAt }); expect(result.status).toBe("stale_generation"); expect((await store.listArtifacts(entry.id)).evidence).toHaveLength(0); });
  it("does not save an old Pattern after Reflection revision", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "A long enough current experience that has specific context and a response." }); const ev = evidence("evidence", entry.id); const ref = reflection("reflection", entry.id, [ev.id]); await store.saveArtifacts(entry.id, { evidence: [ev], reflections: [ref], patterns: [], recoveryTurns: [] }); const packet = createContextPacket({ currentExperience: entry, evidence: [ev], reflections: [ref], locale: "en", requestedTask: "pattern", provider: "mock" }).packet; const snapshot = createGenerationSnapshot(packet); const revised = { ...ref, response: "A revised response", updatedAt: "2026-07-12T02:00:00.000Z" }; await store.saveArtifacts(entry.id, { evidence: [ev], reflections: [revised], patterns: [], recoveryTurns: [] }); expect(isGenerationSnapshotCurrent(snapshot, await store.getExperience(entry.id), await store.listArtifacts(entry.id))).toBe(false); });
});
