export const journeyCopy = {
  en: {
    recreate: "Create a new local-demo candidate", rejectedSummary: "Earlier candidates were not adopted; their rejected text was removed.", rejectedHistory: "Not-adopted candidates (optional)",
    currentSource: "Currently open moment", sameSource: "The candidate quotes your original text above.", viewContent: "View full candidate text", technical: "Technical details (optional)",
    localOrigin: "Local demonstration, not a remote model.", userOrigin: "Written by you", unknownOrigin: "Origin not supplied", editedOrigin: "You corrected the demonstration; its original origin is retained.", responseOrigin: "Response author",
    source: { summary: "A synthetic moment, a reviewed local demonstration, and your own optional reflection.", badge: "Synthetic review build · Local demonstration · Offline",
      limits: "com.lifeos.review.m2c · directFreshV5 · synthetic-only local review. No remote model, providers, credentials, historical context, Pattern, Growth, sync, import/export, backup, migration, repair or production activation. Emulator checks do not prove physical-device or power-loss durability." },
    candidateExplanation: "This local demo starts by quoting your saved text; it does not extract or analyse it with AI. Candidate actions do not edit your original.", correctionLabel: "Candidate text — not your original", correctionHelp: "Saving creates a new candidate revision that still needs your review. Your original text stays unchanged.",
    title: "Clues and reflection", disclosure: "This is local demonstration output, not a remote model. Review before confirming. Confirmation records your acceptance, not independent verification. No diagnosis, identity conclusion or advice.",
    sourceLabel: "Exact source", generate: "Show a local demo candidate", sparse: "This moment is too brief for the existing context gate. You can edit it to add context; nothing has been generated.",
    candidate: "Candidate clue · Local demo", pending: "Awaiting your review", confirmed: "Adopted as a reflection clue · not independently verified", rejected: "Rejected · current candidate text removed", invalidated: "Source changed · no longer used for reflection",
    correct: "Correct candidate", saveCorrection: "Save candidate revision for review", confirm: "Use as a reflection clue", reject: "Do not use", cancel: "Cancel",
    question: "What stands out when you read this evidence again?", ask: "Show a reflection question", reflection: "A question to consider", answerLabel: "Your response (optional)", saveAnswer: "Save my response", skip: "Skip without saving a response", draft: "Response draft · not saved or used as context",
    skipped: "Skipped · no response saved", response: "Your saved response", saved: "This action was saved and reopened", working: "Working · success not yet verified", failed: "Outcome not confirmed. Keep the same request; do not submit a replacement.", conflict: "The source or reviewed version changed. Reopen before taking another action.", retry: "Reconcile the same request", reopen: "Reopen current state", details: "Source information", retention: "Pending corrections keep prior versions locally, outside context. Rejection removes the rejected revision; superseded text remains until this moment is deleted. Editing the source invalidates dependent content. Deleting the moment purges its text and dependent content atomically. No secure physical erasure guarantee.",
  },
  "zh-TW": {
    recreate: "建立新的本機示範候選", rejectedSummary: "先前的候選未採用；被拒絕版本的文字已清除。", rejectedHistory: "不採用紀錄（選看）",
    currentSource: "目前開啟的片刻", sameSource: "候選內容引用上方原文。", viewContent: "查看完整候選內容", technical: "技術資訊（選看）",
    localOrigin: "本機示範內容，不是遠端模型分析。", userOrigin: "由你撰寫", unknownOrigin: "來源未提供", editedOrigin: "你修正了示範文字；原始來源仍保留。", responseOrigin: "回應作者",
    source: { summary: "留下一個合成測試片刻，檢視本機示範內容，再寫下自己的回應（也可以跳過）。", badge: "合成測試審查版 · 本機示範 · 離線",
      limits: "com.lifeos.review.m2c · directFreshV5 · 僅限合成測試資料的本機檢視。不使用遠端模型、Provider、憑證、歷史脈絡、模式假設或成長評估，不提供同步、匯入／匯出、備份、遷移、修復或正式版啟用。模擬器驗證不代表實體手機或斷電耐久性。" },
    candidateExplanation: "這份本機示範起初只引用原文，未進行 AI 整理或分析。候選操作不會修改你的原文。", correctionLabel: "候選內容（不是原文）", correctionHelp: "儲存後會建立候選新版本，仍需你檢視並決定是否採用；原文不會改變。",
    title: "線索與反思", disclosure: "這是本機示範內容，不是遠端模型分析。請先檢視，再決定是否接受；接受只記錄你的選擇，不代表獨立查證。這裡不提供診斷、身分定論或建議。",
    sourceLabel: "來源原文", generate: "顯示本機示範候選", sparse: "這個片刻太簡短，尚未通過既有脈絡檢查。你可以編輯並補充背景；目前沒有產生內容。",
    candidate: "線索候選・本機示範", pending: "等待你檢視", confirmed: "已採用為反思線索 · 不代表獨立查證", rejected: "已拒絕 · 這個候選版本的文字已清除", invalidated: "來源已變更 · 不再用於反思",
    correct: "修正候選內容", saveCorrection: "儲存候選新版本，等待檢視", confirm: "採用為反思線索", reject: "不採用", cancel: "取消",
    question: "再次閱讀這段紀錄時，什麼最讓你留意？", ask: "顯示一個反思問題", reflection: "留給你思考的問題", answerLabel: "你的回應（可不填）", saveAnswer: "儲存我的回應", skip: "跳過，不儲存回應", draft: "回應尚未儲存，也不會用作脈絡",
    skipped: "已跳過 · 沒有儲存回應", response: "你已儲存的回應", saved: "這次操作已儲存並重新讀取確認", working: "處理中 · 尚未確認成功", failed: "結果尚未確認。請保留同一請求，不要另送新請求。", conflict: "來源或已檢視的版本已變更。請重新開啟，再進行操作。", retry: "核對同一請求", reopen: "重新開啟目前狀態", details: "來源資訊", retention: "修正候選內容後，舊版本會留在本機，但不會用作脈絡。拒絕會清除被拒絕版本的文字；已被取代的舊版仍保留到刪除片刻。編輯來源會使相依內容失效；刪除片刻會在同一交易清除原文與相依內容。不保證實體儲存空間已安全抹除。",
  },
  ja: {
    recreate: "端末内デモの候補を新しく作る", rejectedSummary: "以前の候補は採用していません。その版の文章は消去済みです。", rejectedHistory: "採用しなかった候補（任意）",
    currentSource: "いま開いている瞬間", sameSource: "候補は上の原文を引用しています。", viewContent: "候補の全文を見る", technical: "技術情報（任意）",
    localOrigin: "端末内のデモです。遠隔モデルの分析ではありません。", userOrigin: "あなたが書いた内容", unknownOrigin: "作成元の情報なし", editedOrigin: "デモの文章をあなたが修正しました。元の作成情報は保持しています。", responseOrigin: "回答の作成者",
    source: { summary: "合成テスト用の瞬間を残し、端末内のデモ内容を確認して、自分の言葉で振り返ります。回答は任意です。", badge: "合成テスト審査版 · 端末内デモ · オフライン",
      limits: "com.lifeos.review.m2c · directFreshV5 · 合成テストデータの端末内レビューのみ。遠隔モデル、Provider、認証情報、過去の文脈、パターン、成長評価、同期、取り込み／書き出し、バックアップ、移行、修復、正式版の有効化は含みません。エミュレーターでの検証は実機や電源断の耐久性を証明しません。" },
    candidateExplanation: "この端末内デモでは最初に原文を引用するだけで、AIによる整理や分析はしていません。候補への操作で原文が変更されることはありません。", correctionLabel: "候補の文章（原文ではありません）", correctionHelp: "保存すると候補の新版が作られ、改めて確認と採用の選択が必要です。原文は変わりません。",
    title: "手がかりと振り返り", disclosure: "これは端末内のデモであり、遠隔モデルの分析ではありません。確認してから採用を選んでください。採用はあなたの選択の記録であり、独立した事実確認ではありません。診断、人格の断定、助言は行いません。",
    sourceLabel: "元の文章", generate: "端末内デモの候補を表示", sparse: "この文章は短く、既存の文脈チェックを通過していません。背景を追記できます。まだ内容は生成していません。",
    candidate: "手がかりの候補・端末内デモ", pending: "あなたの確認を待っています", confirmed: "振り返りの手がかりに採用済み · 独立した事実確認ではありません", rejected: "却下済み · この候補の版の文章は消去済み", invalidated: "元の文章が変更済み · 振り返りには使いません",
    correct: "候補を修正", saveCorrection: "候補の新版を保存して確認", confirm: "振り返りの手がかりに採用", reject: "採用しない", cancel: "キャンセル",
    question: "この記録を読み返すと、何が最も気になりますか？", ask: "振り返るための問いを表示", reflection: "自分で考えるための問い", answerLabel: "あなたの回答（任意）", saveAnswer: "自分の回答を保存", skip: "回答を保存せずスキップ", draft: "回答は未保存です。文脈にも使われません",
    skipped: "スキップ済み · 回答は保存していません", response: "保存した自分の回答", saved: "この操作を保存し、読み直して確認しました", working: "処理中 · 成功はまだ未確認です", failed: "結果を確認できていません。同じリクエストを保持し、新しいリクエストは送らないでください。", conflict: "元の文章か確認済みの版が変更されました。開き直してから操作してください。", retry: "同じリクエストを確認", reopen: "現在の状態を開き直す", details: "作成元の情報", retention: "候補の修正前の版は端末に残りますが、文脈には使いません。却下した版の文章は消去し、それ以前の版は瞬間の削除まで残ります。元の文章を編集すると依存する内容は無効になります。瞬間の削除は元の文章と依存内容を同じトランザクションで消去します。ストレージの安全な物理消去は保証しません。",
  },
};
