import { describe, expect, it, vi } from "vitest";
import { createArtifactMutationRunner } from "./artifactMutation";
import { createInMemoryLocalEvidenceStore } from "./inMemoryLocalEvidenceStore";
import type { LocalEvidenceStore, PersistedArtifactBundle } from "./types";
import { answerReflectionPrompt } from "../../ai/harness/reflectionResponse";
import { createContextPacket } from "../../ai/harness/contextPacket";
import { createGenerationSnapshot } from "../../ai/harness/generationSnapshot";
import { evidence, provenance, reflection } from "../../test/fixtures";
const empty = (): PersistedArtifactBundle => ({ evidence: [], reflections: [], patterns: [], recoveryTurns: [] });
describe("commit-first artifact mutations", () => {
  it("reports failure, shows no success, and restores durable state", async () => { const base = createInMemoryLocalEvidenceStore(); const entry = await base.createExperience({ body: "body" }); await base.saveArtifacts(entry.id, { ...empty(), evidence: [evidence("one", entry.id)] }); const failing: LocalEvidenceStore = { ...base, saveArtifacts: vi.fn(async () => { throw new Error("disk full"); }) }; const committed: PersistedArtifactBundle[] = []; const errors: unknown[] = []; const run = createArtifactMutationRunner({ store: failing, onCommitted: (_, bundle) => committed.push(bundle), onError: (error) => errors.push(error) }); const result = await run(entry.id, (current) => ({ ...current, evidence: [] })); expect(result.status).toBe("failed"); expect(errors).toHaveLength(1); expect(committed[committed.length - 1]?.evidence.map((x) => x.id)).toEqual(["one"]); });
  it("serializes rapid sequential mutations without lost updates", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "body" }); const run = createArtifactMutationRunner({ store, onCommitted: () => undefined, onError: () => undefined }); await Promise.all([run(entry.id, (current) => ({ ...current, evidence: [...current.evidence, evidence("one", entry.id)] })), run(entry.id, (current) => ({ ...current, evidence: [...current.evidence, evidence("two", entry.id)] }))]); expect((await store.listArtifacts(entry.id)).evidence.map((x) => x.id)).toEqual(["one", "two"]); });
  it("does not restore rejected data during an immediate next action", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "body" }); await store.saveArtifacts(entry.id, { ...empty(), evidence: [evidence("reject", entry.id), evidence("keep", entry.id, "candidate")] }); const run = createArtifactMutationRunner({ store, onCommitted: () => undefined, onError: () => undefined }); await Promise.all([run(entry.id, (current) => ({ ...current, evidence: current.evidence.filter((x) => x.id !== "reject") })), run(entry.id, (current) => ({ ...current, evidence: current.evidence.map((x) => x.id === "keep" ? { ...x, status: "confirmed" as const } : x) }))]); const saved = await store.listArtifacts(entry.id); expect(saved.evidence.map((x) => x.id)).toEqual(["keep"]); expect(saved.evidence[0].status).toBe("confirmed"); });
  it("revalidates a Pattern snapshot after a queued Reflection revision", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "A sufficiently detailed entry for deterministic generation." }); const ev = evidence("evidence", entry.id); const prompt = reflection("reflection", entry.id, [ev.id]); await store.saveArtifacts(entry.id, { ...empty(), evidence: [ev], reflections: [prompt] }); const snapshot = createGenerationSnapshot(createContextPacket({ currentExperience: entry, evidence: [ev], reflections: [prompt], locale: "en", requestedTask: "pattern", provider: "mock" }).packet); const run = createArtifactMutationRunner({ store, onCommitted: () => undefined, onError: () => undefined }); const revise = run(entry.id, (current) => ({ ...current, reflections: current.reflections.map((item) => item.id === prompt.id ? answerReflectionPrompt(item, "Revised before the Pattern result", "2026-07-12T04:00:00.000Z") : item), patterns: [] })); const latePattern = run(entry.id, (current) => ({ ...current, patterns: [{ id: "late-pattern", sourceEntryId: entry.id, sourceEvidenceIds: [ev.id], sourceReflectionPromptIds: [prompt.id], text: "Late hypothesis", status: "candidate", provenance: provenance(entry.id), createdAt: "2026-07-12T00:00:00.000Z", updatedAt: "2026-07-12T00:00:00.000Z" }] }), { generationSnapshot: snapshot }); await revise; expect((await latePattern).status).toBe("stale_generation"); expect((await store.listArtifacts(entry.id)).patterns).toHaveLength(0); });
  it("discards a late Reflection result after queued Evidence rejection", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "A sufficiently detailed entry for deterministic generation." }); const ev = evidence("evidence", entry.id); await store.saveArtifacts(entry.id, { ...empty(), evidence: [ev] }); const snapshot = createGenerationSnapshot(createContextPacket({ currentExperience: entry, evidence: [ev], locale: "en", requestedTask: "reflection", provider: "mock" }).packet); const run = createArtifactMutationRunner({ store, onCommitted: () => undefined, onError: () => undefined }); const reject = run(entry.id, (current) => ({ ...current, evidence: [], reflections: [], patterns: [] })); const lateReflection = run(entry.id, (current) => ({ ...current, reflections: [reflection("late-reflection", entry.id, [ev.id])] }), { generationSnapshot: snapshot }); await reject; expect((await lateReflection).status).toBe("stale_generation"); expect((await store.listArtifacts(entry.id)).reflections).toHaveLength(0); });
  it("commits a current generation snapshot", async () => { const store = createInMemoryLocalEvidenceStore(); const entry = await store.createExperience({ body: "A sufficiently detailed entry for deterministic generation." }); const ev = evidence("evidence", entry.id); await store.saveArtifacts(entry.id, { ...empty(), evidence: [ev] }); const snapshot = createGenerationSnapshot(createContextPacket({ currentExperience: entry, evidence: [ev], locale: "en", requestedTask: "reflection", provider: "mock" }).packet); const run = createArtifactMutationRunner({ store, onCommitted: () => undefined, onError: () => undefined }); const result = await run(entry.id, (current) => ({ ...current, reflections: [reflection("generated-reflection", entry.id, [ev.id])] }), { generationSnapshot: snapshot }); expect(result.status).toBe("committed"); expect((await store.listArtifacts(entry.id)).reflections.map((item) => item.id)).toEqual(["generated-reflection"]); });
});
